apiVersion: skaffold/v4beta6
kind: Config
metadata:
  name: buildpacks-node-tutorial
build:
  artifacts:
    - image: skaffold-buildpacks-node
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - k8s/web.yaml
